Repository sciwork/swportal, pull requests merged in 2021-08, with the labels that each got.

#75 [event] add end of August devenv sprint
  content/pages/sprint/2021/08.rst
  content/pages/sprint/index.rst
Labels: sprint

#78 Publish on 8/5
  content/pages/sprint/2021/08.rst
  content/pages/sprint/index.rst
Labels: publish

#77 Add 08early-pycht sprint
  content/pages/sprint/2021/08mid-pycht.rst
  content/pages/sprint/index.rst
Labels: sprint

#80 Publish on 8/9
  content/pages/sprint/2021/08mid-pycht.rst
  content/pages/sprint/index.rst
Labels: publish

#79 fix <li> indentation
  tailwind/styles.css
  theme/static/css/main.css
Labels: bug, stylesheet

#81 [event] 08mid pycht meeting minutes
  content/pages/sprint/2021/08mid-pycht.rst
Labels: sprint

#82 Publish on 8/15
  content/pages/sprint/2021/08mid-pycht.rst
  tailwind/styles.css
  theme/static/css/main.css
Labels: publish

#84 Publish on 8/22
  content/pages/sprint/2021/08.rst
Labels: publish
