Repository sciwork/swportal, pull requests merged in 2022-09, with the labels that each got.

#130 add meetup page
  content/pages/meetup/insex.rst
  pelicanconf.py
Labels: enhancement

#126 [09-hsinchu] Create sprint page
  content/pages/sprint/2022/09-hsinchu.rst
  content/pages/sprint/index.rst
Labels: sprint

#133 Publish on 9/12
  content/pages/sprint/2022/09-hsinchu.rst
  content/pages/sprint/index.rst
  tailwind/styles.css
  tailwind/tailwind.config.js
  theme/static/css/main.css
Labels: publish

#137 Add the web page for October meetup
  content/pages/meetup/2022/10-nycu.rst
  content/pages/meetup/index.rst
  content/pages/meetup/insex.rst
Labels: meetup

#138 Publish 9/15
  content/pages/meetup/2022/10-nycu.rst
  content/pages/meetup/index.rst
  content/pages/meetup/insex.rst
Labels: publish, meetup

#139 Maintenance change
  .gitignore
  content/pages/meetup/2022/10-nycu.rst
Labels: bug

#140 Publish on 9/16
  .gitignore
  content/pages/meetup/2022/10-nycu.rst
Labels: publish

#142 [meetup 2210] Add panelist company information
  content/pages/meetup/2022/10-nycu.rst
Labels: meetup

#144 add sitemap plugin for generating sitemap.xml
  README.rst
  content/pages/meetup/index.rst
  content/pages/sprint/index.rst
  pelican-plugins/sitemap/__init__.py
  pelican-plugins/sitemap/sitemap.py
  pelicanconf.py
Labels: enhancement

#145 Publish on 9/25
  README.rst
  content/pages/meetup/index.rst
  content/pages/sprint/index.rst
  pelican-plugins/sitemap/__init__.py
  pelican-plugins/sitemap/sitemap.py
  pelicanconf.py
Labels: publish
