Repository sciwork/swportal, pull requests merged in 2023-09, with the labels that each got.

#249 add the sprint202309 page
  content/pages/project.rst
  content/pages/sprint/2023/09-hsinchu.rst
  content/pages/sprint/index.rst
Labels: sprint

#253 Publish on 9/5
  content/pages/project.rst
  content/pages/sprint/2023/09-hsinchu.rst
  content/pages/sprint/index.rst
Labels: publish

#255 add 0913 meetup page
  content/pages/meetup/2023/0913-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#256 Publish on 9/11
  content/pages/meetup/2023/0913-nycu.rst
  content/pages/meetup/index.rst
Labels: publish

#258 Publish on 9/17
  content/pages/meetup/2023/0920-nycu.rst
  content/pages/meetup/index.rst
Labels: publish

#261 Publish on 9/25
  content/pages/meetup/2023/0927-nycu.rst
  content/pages/meetup/index.rst
Labels: publish

#264 Publish on 09/28
  content/pages/conference/index.rst
  pelicanconf.py
Labels: publish

#262 add page of 20231022 pydoc-zhtw meetup
  content/pages/meetup/2023/1022-pydoc.rst
  content/pages/meetup/index.rst
Labels: sprint

#265 Publish on 9/29
  content/pages/meetup/2023/1022-pydoc.rst
  content/pages/meetup/index.rst
Labels: publish

#267 Publish on 9/29
  content/pages/conference/index.rst
Labels: publish
