Repository sciwork/swportal, pull requests merged in 2023-12, with the labels that each got.

#306 FEATURE: add the 20231213 meetup page
  content/pages/meetup/2023/1213-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#308 Publish on 12/8
  content/pages/sprint/2023/12-taipei.rst
  content/pages/sprint/index.rst
Labels: publish

#309 FEATURE: add the 20231220 meetup page
  content/pages/meetup/2023/1220-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#310 Publish on 12/15
  content/pages/meetup/2023/1220-nycu.rst
  content/pages/meetup/index.rst
Labels: publish

#287 Feature/sprint202311: we modify the introduction of the project list
  content/pages/project.rst
Labels: enhancement

#314 FEATURE: add the 20231227 meetup page
  content/pages/meetup/2023/1227-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#315 Publish on 12/23
  content/pages/meetup/2023/1227-nycu.rst
  content/pages/meetup/index.rst
Labels: publish

#317 Publish sciwork 2023 report on 12/23
  content/pages/conference/2023/report.rst
  content/pages/conference/2023/talk-in-a-snapshot.png
  content/pages/conference/index.rst
Labels: publish

#318 FEATURE: add the 2024 sprint placefolder page and the corresponding s…
  content/pages/sprint/2024/01-hsinchu.rst
  content/pages/sprint/2024/02-hsinchu.rst
  content/pages/sprint/2024/03-hsinchu.rst
  content/pages/sprint/2024/04-hsinchu.rst
  content/pages/sprint/2024/05-hsinchu.rst
  content/pages/sprint/index.rst
Labels: sprint

#319 Publish on 12/25
  content/pages/sprint/2024/01-hsinchu.rst
  content/pages/sprint/2024/02-hsinchu.rst
  content/pages/sprint/2024/03-hsinchu.rst
  content/pages/sprint/2024/04-hsinchu.rst
  content/pages/sprint/2024/05-hsinchu.rst
  content/pages/sprint/index.rst
Labels: publish
