Repository sciwork/swportal, pull requests merged in 2023-07, with the labels that each got.

#213 Publish on 7/8
  content/pages/meetup/2023/0712-nycu.rst
  content/pages/meetup/index.rst
Labels: publish

#214 Add meetup 0705 photos and adjust web layout for meetup 0712
  content/pages/meetup/2023/0705-nycu.rst
  content/pages/meetup/2023/0712-nycu.rst
Labels: meetup

#215 Publish on 7/9
  content/pages/meetup/2023/0705-nycu.rst
  content/pages/meetup/2023/0712-nycu.rst
Labels: publish

#216 Feature/meetup0719
  content/pages/meetup/2023/0719-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#217 Publish on 7/17
  content/pages/meetup/2023/0719-nycu.rst
  content/pages/meetup/index.rst
Labels: publish

#220 Publish on 07/20
  content/pages/project.rst
Labels: publish

#223 Publish on 7/21
  content/pages/meetup/2023/0726-nycu.rst
  content/pages/meetup/index.rst
Labels: publish

#225 feature/meetup/0726: add a session for sciwork grand project
  content/pages/meetup/2023/0726-nycu.rst
Labels: meetup

#226 Publish on 7/23
  content/pages/meetup/2023/0726-nycu.rst
  content/pages/meetup/2023/0805-pydoc.rst
  content/pages/meetup/index.rst
Labels: publish

#228 Publish on 7/26
  Pipfile.lock
  content/pages/sprint/2023/08-hsinchu.rst
  content/pages/sprint/index.rst
Labels: publish

#230 Publish on 7/28
  content/pages/sprint/2023/08-hsinchu.rst
Labels: publish

#231 Feature/meetup/0802
  content/pages/meetup/2023/0802-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#233 hotfix remove the braces that not belong to ASCII
  content/pages/sprint/2023/08-hsinchu.rst
Labels: sprint

#234 Publish on 7/30
  content/pages/meetup/2023/0802-nycu.rst
  content/pages/meetup/index.rst
  content/pages/sprint/2023/08-hsinchu.rst
Labels: publish
