Repository sciwork/swportal, pull requests merged in 2024-07, with the labels that each got.

#428 update: update the sign up discord link at 20240710 meetup page
  content/pages/meetup/2024/0710-nycu.rst
Labels: meetup

#429 Publish on 7/8
  content/pages/meetup/2024/0710-nycu.rst
Labels: publish

#431 fix(theme): adjust padding for menu items
  theme/templates/base.html
Labels: bug

#434 feat: add the 20240724 meetup page
  content/pages/meetup/2024/0724-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#435 Publish on 7/22
  content/pages/meetup/2024/0724-nycu.rst
  content/pages/meetup/index.rst
Labels: publish

#436 feat: add the 20240731 meetup page
  content/pages/meetup/2024/0731-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#439 Publish on 7/28
  content/pages/index.rst
  content/pages/meetup/2024/0731-nycu.rst
  content/pages/meetup/index.rst
  content/pages/sprint/2024/08-coscup.rst
  content/pages/sprint/2024/08-taipei.rst
  content/pages/sprint/index.rst
Labels: publish
