Repository sciwork/swportal, pull requests merged in 2024-02, with the labels that each got.

#348 Publish on 2/2
  content/pages/sprint/2024/02-hsinchu.rst
Labels: publish

#350 Publish on 2/6
  content/pages/sprint/2024/03-Kaohsiung.rst
  content/pages/sprint/index.rst
  tailwind/tailwind.config.js
  theme/static/css/main.css
Labels: publish

#352 Publish on 2/7
  content/pages/sprint/2024/02-hsinchu.rst
Labels: publish

#353 DELETE: delete the 20240228 meetup page
  content/pages/meetup/2024/0228-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#354 UPDATE: add the information of the project list, venue, and sign up link
  content/pages/sprint/2024/03-Kaohsiung.rst
Labels: sprint

#355 Publish on 2/15
  content/pages/meetup/2024/0228-nycu.rst
  content/pages/meetup/index.rst
  content/pages/sprint/2024/03-Kaohsiung.rst
Labels: publish

#357 Publish on 2/20
  content/pages/meetup/2024/0310-pydoc.rst
  content/pages/meetup/index.rst
Labels: publish

#359 DELETE: remove the 2403 Kaohsiung seminar page
  content/pages/sprint/2024/03-Kaohsiung.rst
  content/pages/sprint/index.rst
Labels: seminar

#360 Publish on 2/25
  content/pages/sprint/2024/03-Kaohsiung.rst
  content/pages/sprint/index.rst
Labels: publish

#362 Publish on 2/28
  content/pages/conference/03-workshop.rst
  content/pages/conference/index.rst
Labels: publish

#364 Publish on 2/28 hotfix
  content/pages/conference/2024/03-workshop.rst
  content/pages/conference/index.rst
Labels: publish

#366 Publish on 2/29
  content/pages/conference/2024/03-workshop.rst
  content/pages/conference/index.rst
Labels: publish
