Repository sciwork/swportal, pull requests merged in 2024-08, with the labels that each got.

#442 Publish on 08/01
  content/images/coscup-CareerRoundtable-1.jpeg
  content/images/coscup-CareerRoundtable-2.jpeg
  content/pages/sprint/2024/08-coscup.rst
Labels: publish

#443 feat: add the 20240807 meetup page
  content/pages/meetup/2024/0807-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#444 Publish on 8/7
  content/pages/meetup/2024/0807-nycu.rst
  content/pages/meetup/index.rst
Labels: publish

#447 Publish on 8/12
  content/pages/meetup/2024/0814-nycu.rst
  content/pages/meetup/index.rst
  content/pages/sprint/2024/08-taipei.rst
  content/pages/sprint/index.rst
Labels: publish

#449 feat(meetup): add the 20240821 meetup page
  content/pages/meetup/2024/0821-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#450 Publish on 8/20
  content/pages/meetup/2024/0821-nycu.rst
  content/pages/meetup/index.rst
Labels: publish

#452 Publish on 08/23
  content/pages/index.rst
  content/pages/sprint/2024/09-hsinchu.rst
  content/pages/sprint/index.rst
Labels: publish

#453 Update project information for sprint-2409
  content/pages/index.rst
  content/pages/sprint/2024/09-hsinchu.rst
Labels: sprint

#454 Publish on 08/23
  content/pages/index.rst
  content/pages/sprint/2024/09-hsinchu.rst
Labels: publish

#456 Update 20240828 meetup information
  content/pages/meetup/2024/0828-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#457 Publish on 08/27
  content/pages/meetup/2024/0828-nycu.rst
  content/pages/meetup/index.rst
Labels: publish
