Repository sciwork/swportal, pull requests merged in 2024-05, with the labels that each got.

#395 Publish on 5/4
  content/pages/conference/2024/03-workshop.rst
  content/pages/sprint/2023/08-hsinchu.rst
  content/pages/sprint/2023/09-hsinchu.rst
  content/pages/sprint/2023/10-hsinchu.rst
  content/pages/sprint/2023/11-hsinchu.rst
  content/pages/sprint/2023/12-taipei.rst
  content/pages/sprint/2024/01-hsinchu.rst
  content/pages/sprint/2024/02-hsinchu.rst
  content/pages/sprint/2024/03-taipei.rst
  content/pages/sprint/2024/04-hsinchu.rst
  content/pages/sprint/2024/05-hsinchu.rst
  content/pages/sprint/2024/06-taipei.rst
  content/pages/sprint/index.rst
Labels: publish

#396 update: add the sign up discord link at 20240508 meetup page
  content/pages/meetup/2024/0508-nycu.rst
Labels: meetup

#397 Publish on 5/5
  content/pages/meetup/2024/0508-nycu.rst
Labels: publish

#399 update: modify the discord sign up link in 20240514 meetup page
  content/pages/meetup/2024/0515-nycu.rst
Labels: meetup

#400 Publish on 5/9
  content/pages/meetup/2024/0515-nycu.rst
Labels: publish

#402 Publish on 5/10
  content/pages/sprint/2024/05-hsinchu.rst
Labels: publish

#403 feat: add the February and March review blog
  content/blog/2024/202402-03-review.rst
Labels: blog

#404 Publish on 5/15
  content/blog/2024/202402-03-review.rst
  content/pages/conference/2024/06-seminar.rst
  content/pages/conference/index.rst
  tailwind/styles.css
  theme/static/css/main.css
Labels: publish

#406 Publish on 5/15
  content/pages/sprint/2024/06-taipei.rst
  content/pages/sprint/index.rst
Labels: publish

#407 update: update the discord sign up link in the 0522 meetup page
  content/pages/meetup/2024/0522-nycu.rst
  content/pages/meetup/2024/0529-nycu.rst
Labels: meetup

#408 Publish on 5/17
  content/pages/meetup/2024/0522-nycu.rst
  content/pages/meetup/2024/0529-nycu.rst
Labels: publish

#410 Publish on 5/19
  content/pages/conference/2024/06-seminar.rst
Labels: publish

#411 update: add the sign up discord link and modify the description of subject of automation discussion
  content/pages/meetup/2024/0529-nycu.rst
Labels: meetup

#412 Publish on 5/23
  content/pages/meetup/2024/0529-nycu.rst
Labels: publish

#414 Publish on 5/29
  content/pages/conference/2024/06-seminar.rst
  content/pages/index.rst
Labels: publish

#415 feat: add the 202406 meetup page and update meetup index
  content/pages/meetup/2024/0605-nycu.rst
  content/pages/meetup/2024/0612-nycu.rst
  content/pages/meetup/2024/0619-nycu.rst
  content/pages/meetup/2024/0626-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#416 Publish on 5/30
  content/pages/meetup/2024/0605-nycu.rst
  content/pages/meetup/2024/0612-nycu.rst
  content/pages/meetup/2024/0619-nycu.rst
  content/pages/meetup/2024/0626-nycu.rst
  content/pages/meetup/index.rst
Labels: publish
