Repository sciwork/swportal, pull requests merged in 2024-11, with the labels that each got.

#497 Drop the definite article before sciwork
  content/pages/index.rst
Labels: bug

#498 Publish on 11/3
  content/pages/index.rst
Labels: publish

#499 Docs: Add the agenda of 1113 meetup
  content/pages/meetup/2024/1113-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#500 Publish Docs: Add the agenda of 1113 meetup
  content/pages/meetup/2024/1113-nycu.rst
  content/pages/meetup/index.rst
Labels: publish

#501 Docs: Add the agenda of 1120 meetup
  content/pages/meetup/2024/1120-nycu.rst
  content/pages/meetup/index.rst
Labels: documentation

#502 Publish: Create new footer and add the agenda of 1120 meetup
  content/pages/meetup/2024/1120-nycu.rst
  content/pages/meetup/index.rst
  theme/static/css/main.css
  theme/templates/base.html
Labels: publish

#504 Publish Docs: Add the page of 1127 meetup
  content/pages/meetup/2024/1127-nycu.rst
  content/pages/meetup/index.rst
Labels: publish
