Repository sciwork/swportal, pull requests merged in 2024-06, with the labels that each got.

#418 update: update the discord sign up link and description of meetup auto discussion
  content/pages/meetup/2024/0612-nycu.rst
Labels: meetup

#419 Publish on 6/7
  content/pages/meetup/2024/0612-nycu.rst
Labels: publish

#417 feat(seminar): update agenda and information
  content/pages/conference/2024/06-seminar.rst
Labels: seminar

#420 Publish on 6/8
  content/pages/conference/2024/06-seminar.rst
Labels: publish

#422 Publish on 6/13
  content/pages/meetup/2024/0619-nycu.rst
  content/pages/meetup/2024/0626-nycu.rst
Labels: publish

#426 feat: add the July meetup page
  content/pages/meetup/2024/0703-nycu.rst
  content/pages/meetup/2024/0710-nycu.rst
  content/pages/meetup/2024/0717-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#427 Publish on 6/30
  content/pages/index.rst
  content/pages/meetup/2024/0703-nycu.rst
  content/pages/meetup/2024/0710-nycu.rst
  content/pages/meetup/2024/0717-nycu.rst
  content/pages/meetup/index.rst
  content/pages/sprint/2024/07-taipei.rst
  content/pages/sprint/2024/08-taipei.rst
  content/pages/sprint/index.rst
Labels: publish
