Repository sciwork/swportal, pull requests merged in 2025-03, with the labels that each got.

#560 Docs: Add the 0305 meetup page
  content/pages/meetup/2025/0305-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#561 Publish: Add the 0305 meetup page
  content/pages/meetup/2025/0305-nycu.rst
  content/pages/meetup/index.rst
Labels: publish

#562 feature: Add agenda on 20250305 meetup
  content/pages/meetup/2025/0305-nycu.rst
Labels: meetup

#563 Publish: add SITCON page and update 0305 meetup schedule
  content/pages/conference/2025/03-sitcon.rst
  content/pages/conference/index.rst
  content/pages/meetup/2025/0305-nycu.rst
Labels: publish

#564 feature: change timeslot for PUI agenda
  content/pages/meetup/2025/0305-nycu.rst
Labels: meetup

#565 Publish: update 0305 meetup time table
  content/pages/meetup/2025/0305-nycu.rst
Labels: publish

#572 Docs:Add the page of 0312 meetup
  content/pages/meetup/2025/0312-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#573 Publish: Add the page of 0312 meetup
  content/pages/meetup/2025/0312-nycu.rst
  content/pages/meetup/index.rst
Labels: publish

#574 docs: add K8s section to 0312 meetup
  content/pages/meetup/2025/0312-nycu.rst
  theme/static/css/main.css
Labels: meetup

#580 Meetup: Add the 0319 meetup page
  content/pages/meetup/2025/0319-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#581 feat: add Hsinchu sprint to upcoming events and improve visual design
  content/pages/index.rst
  theme/static/css/main.css
Labels: enhancement, stylesheet

#583 Publish on 3/16
  content/pages/index.rst
  theme/static/css/main.css
Labels: publish

#586 Docs: Create the meetup page of next Wednesday
  content/pages/index.rst
  content/pages/meetup/2025/0326-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#590 Publish: Create the meetup of next Wednesday
  content/pages/index.rst
  content/pages/meetup/2025/0326-nycu.rst
  content/pages/meetup/index.rst
Labels: publish

#591 Fix: Fix the wrong link of the upcoming event.
  content/pages/index.rst
Labels: meetup

#592 Publish: Fix the wrong link of the upcoming event.
  content/pages/index.rst
Labels: publish

#593 Add the meetup page in April second.
  content/pages/index.rst
  content/pages/meetup/2025/0402-nycu.rst
  content/pages/meetup/index.rst
Labels: meetup

#594 Publish: Add the meetup page in April second.
  content/pages/index.rst
  content/pages/meetup/2025/0402-nycu.rst
  content/pages/meetup/index.rst
Labels: publish
